### ISSUE TITLE
issue with gem dependencies

### ISSUE THREAD

**Issue by cupofcake92** [learn-co-curriculum/sinatra-activerecord-using-tux#24]
Hi - I ran into a similar issue yesterday when trying to run a lab. Had to talk to a tech person. Something is going on in the file in the gem dependencies, had to change line 3  from:
gem 'activerecord', :require => 'active_record'
to
gem 'activerecord', '4.2', :require => 'active_record'

in order for tux to work. Otherwise there's a huge error: 
NoMethodError: undefined method `needs_migration?' for ActiveRecord::Migrator:Class
  /usr/local/rvm/gems/ruby-2.3.1/gems/ripl-rack-0.2.0/lib/ripl/rack.rb:38:in `eval'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
  (eval):1:in `new'
  (eval):1:in `initialize'
  /usr/local/rvm/gems/ruby-2.3.1/gems/ripl-rack-0.2.0/lib/ripl/rack.rb:38:in `eval'
  /usr/local/rvm/gems/ruby-2.3.1/gems/ripl-rack-0.2.0/lib/ripl/rack.rb:38:in `initialize'...

Hopefully it can be fixed so other students don't run into the same error. Thanks!

**Comment by drakeltheryuujin** [comment]
Hi @dani8439,

We've updated the materials to fix this issue. If you don't think that it's been resolved, please reopen this issue and we'll take another look. 

Thanks for contributing! 💙
