### ISSUE TITLE
"bundle install" fails with: requested: activerecord = 4.2  [but]...activerecord locked at 5.0.0. 

### ISSUE THREAD

**Issue by kjoewill** [learn-co-curriculum/sinatra-activerecord-using-tux#25]
I forked and then cloned the lab from GitHub then ran "bundle install" and received this error message:

> You have requested:
>   activerecord = 4.2
> 
> The bundle currently has activerecord locked at 5.0.0.
> Try running `bundle update activerecord` 

I notice that the gemfile specifies AR 4.2 yet the gemfile.lock specifies 5.0.0.  Running the suggested command foeced the gemfile.lock back to 4.2 and I seem to be up and running now.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
