### ISSUE TITLE
Several issues before Tux would run

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/sinatra-activerecord-using-tux#26]
Hey there, 

I couldn't get Tux to run when I initially ran the command after opening the lab. Here's what I had to do to get it to run (some with the help of a technical coach): 

- Delete the Gemfile.lock
- Update the ActiveRecord gem version `gem 'activerecord', '~> 5.2', '>= 5.2.3', :require => 'active_record'`
- Change the sqlite3 gem to `gem 'sqlite3', '~> 1.3.7'`
- Change line 3 of config.ru to `if ActiveRecord::Base.connection.migration_context.needs_migration?`
- Change line 1 of the migration to `class CreateUsers < ActiveRecord::Migration[4.2]`
- Delete schema.rb and development.sqlite files

That seemed to get it to work, but the lab should probably be updated to reflect those changes for other students.

Best, 
A

**Comment by ivalentine** [comment]
I encountered this issue with @nicobazzoni today. As of today, the above solution still works.

**Comment by ivalentine** [comment]
I encountered this issue with @luciana-lab today. As of today, the above solution still works.
