### ISSUE TITLE
Missing migration.

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/sinatra-activerecord-using-tux#4]
The lab's README.md reads:

"Starter Code

We've included two migration files, 20150916143412_create_posts.rb and 20150916143408_create_users.rb, which will create tables for posts and users, respectively."

but './db/migrate' only has one migration (20150916143408_create_users.rb) to create the "users" table. I'll try to make my own second migration for now, but seems like the README might need to be updated, or new migration be made.

**Comment by victhevenot** [comment]
hey @onyoo thanks so much for pointing this out to us!  Migrations and readme are now updated/
