### ISSUE TITLE
No local tests

### ISSUE THREAD

**Issue by mmmeyers** [learn-co-curriculum/sinatra-activerecord-using-tux#6]
The right rail has "Your local tests have not been run" but there are no specs in the directory, so there is no way to get a green light here.

**Comment by AnnJohn** [comment]
Hi @mmmeyers sorry for that. We just changed the lesson to a Readme and not a Lab so it should be ok now. Thanks.

**Comment by mmmeyers** [comment]
Hi @AnnJohn - thank you! It shows that I "finished reading" in the actual lesson now but in the drop-down list of lessons, it still shows this one as not completed - any way to fix that?
