### ISSUE TITLE
None of the migrations are correct

### ISSUE THREAD

**Issue by dannyd4315** [learn-co-curriculum/sinatra-activerecord-using-tux#7]
None of the migrations that are talked about in the README are correct and the current schema does not match up with the lesson.

**Comment by AnnJohn** [comment]
thanks @dannyd4315. we'll look into this one as quickly as we can.

**Comment by victhevenot** [comment]
Hi @dannyd4315. Thanks for noting this issue. Seems we got our wires crossed with versions of this README. working on fixing this now!

**Comment by AnnJohn** [comment]
hi @dannyd4315 we fixed this so that the deployed version is the same as the canonical learn-co-curriculum version. thanks!
