### ISSUE TITLE
Terminal screenshots show shotgun rather than IRB or Tux console

### ISSUE THREAD

**Issue by alexbarron** [learn-co-curriculum/sinatra-activerecord-using-tux#9]
I noticed a couple of the screenshots on this lesson aren't showing the right material.

Screenshot #1 is supposed to show IRB and requiring /models/user.rb but actual screenshot shows a shotgun server loading.

Screenshot #3 is supposed to show opening the Tux console but actual screenshot shows a rackup app.rb command running.

**Comment by AnnJohn** [comment]
thank you @alexbarron. We'll update these soon.
